DROP TABLE EMPLEADO;
DROP TABLE PROYECTO;
DROP TABLE DEPARTAMENTO;


CREATE TABLE DEPARTAMENTO
   (    NUM_DEPARTAMENTO    NUMBER, 
	    NOMBRE_DEPARTAMENTO VARCHAR2(20 BYTE),
        PLANTA NUMBER,
        EDIFICIO VARCHAR2(30 BYTE),
        CIUDAD_DPT VARCHAR2(20 BYTE)
    );

CREATE TABLE PROYECTO
   (    NUM_PROYECTO    NUMBER, 
	    NOMBRE_PROYECTO VARCHAR2(10 BYTE),
        PRODUCTO VARCHAR2(20 BYTE),
        PRESUPUESTO NUMBER
    );
    
CREATE TABLE EMPLEADO
   (    NUM_EMPLEADO    NUMBER, 
	    NOMBRE_EMPLEADO VARCHAR2(30 BYTE),
        SUELDO NUMBER,
        CIUDAD_EMP VARCHAR2(20 BYTE),
        NUM_DEPARTAMENTO NUMBER,
        NUM_PROYECTO NUMBER
    );    


  ALTER TABLE EMPLEADO ADD 
  CONSTRAINT EMPLEADO_PK 
  PRIMARY KEY(NUM_EMPLEADO); 
  
  ALTER TABLE DEPARTAMENTO ADD 
  CONSTRAINT DEPARTAMENTO_PK 
  PRIMARY KEY(NUM_DEPARTAMENTO ); 
 
  ALTER TABLE PROYECTO ADD 
  CONSTRAINT PROYECTO_PK 
  PRIMARY KEY(NUM_PROYECTO); 
  
 ----------------------------------------------------
 
 ALTER TABLE EMPLEADO ADD (
  CONSTRAINT EMPLEADO_DEPARTAMENTO_FK 
 FOREIGN KEY (NUM_DEPARTAMENTO ) 
 REFERENCES DEPARTAMENTO (NUM_DEPARTAMENTO ));
 

  ALTER TABLE EMPLEADO ADD (
  CONSTRAINT EMPLEADO_PROYECTO_FK 
 FOREIGN KEY (NUM_PROYECTO ) 
 REFERENCES PROYECTO (NUM_PROYECTO ));